#=========================================[ Vault Helm Chart Value Overrides ]
global:
  enabled: true
  tlsDisable: true

injector:
  enabled: true
  # Use the Vault K8s Image https://github.com/hashicorp/vault-k8s/
  image:
    repository: "192.168.1.10:8083/hashicorp/vault-k8s"
    tag: "1.2.1"

  resources:
      requests:
        memory: 50Mi
        cpu: 50m
      limits:
        memory: 256Mi
        cpu: 250m

server:
  image:
    repository: "192.168.1.10:8083/hashicorp/vault"
    tag: "1.14.0"
  resources:
     requests:
       memory: 50Mi
       cpu: 500m
     limits:
       memory: 16Gi
       cpu: 2000m
  readinessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
  livenessProbe:
    enabled: true
    path: "/v1/sys/health?standbyok=true"
    initialDelaySeconds: 360
  standalone:
    enabled: false
  ha:
    enabled: true
    replicas: 3
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address     = "0.0.0.0:8200"
      }

      storage "consul" {
        path = "vault"
        address = "consul-consul-server:8500"
      }

# Vault UI
ui:
  enabled: true
  externalPort: 8200
