image:
  registry: 192.168.1.10:8083
  repository: bitnami/nginx-ingress-controller
  tag: 1.9.3-debian-11-r0
  chroot: false
  pullPolicy: IfNotPresent
  runAsUser: 101
  allowPrivilegeEscalation: true
  containerName: controller
  containerPort:
    http: 80
    https: 443
  metrics:
  port: 10254
  portName: metrics
  enabled: true
  serviceMonitor:
    enabled: true

defaultBackend:
  image:
    registry: 192.168.1.10:8083
    repository: bitnami/nginx
    tag: 1.25.2-debian-11-r47
