#-------------------------------------[Set custom images]
image:
  longhorn:
    engine:
      repository: 192.168.1.10:8083/longhornio/longhorn-engine
      tag: v1.6.0
    manager:
      repository: 192.168.1.10:8083/longhornio/longhorn-manager
      tag: v1.6.0
    ui:
      repository: 192.168.1.10:8083/longhornio/longhorn-ui
      tag: v1.6.0
    instanceManager:
      repository: 192.168.1.10:8083/longhornio/longhorn-instance-manager
      tag: v1.6.0
    shareManager:
      repository: 192.168.1.10:8083/longhornio/longhorn-share-manager
      tag: v1.6.0
    backingImageManager:
      repository: 192.168.1.10:8083/longhornio/backing-image-manager
      tag: v1.6.0
    supportBundleKit:
      repository: 192.168.1.10:8083/longhornio/support-bundle-kit
      tag: v0.0.33
  csi:
    attacher:
      repository: 192.168.1.10:8083/longhornio/csi-attacher
      tag: v4.4.2
    provisioner:
      repository: 192.168.1.10:8083/longhornio/csi-provisioner
      tag: v3.6.2
    nodeDriverRegistrar:
      repository: 192.168.1.10:8083/longhornio/csi-node-driver-registrar
      tag: v2.9.2
    resizer:
      repository: 192.168.1.10:8083/longhornio/csi-resizer
      tag: v1.9.2
    snapshotter:
      repository: 192.168.1.10:8083/longhornio/csi-snapshotter
      tag: v6.3.2
    livenessProbe:
      repository: 192.168.1.10:8083/longhornio/livenessprobe
      tag: v2.11.0
  pullPolicy: IfNotPresent
#====================================[Other Options]
persistence:
  defaultClassReplicaCount: 2
defaultSettings:
  defaultDataPath: /longhorn
